=== ericdaugherty/ericdaugherty.github.io/trainschedule/trainschedule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by Eric Daugherty (XiWare Corp) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="schedule">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="route" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="inbound" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="days"/>
										<xs:element ref="stops"/>
										<xs:element ref="trains"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="outbound" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="days"/>
										<xs:element ref="stops"/>
										<xs:element ref="trains"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="stops">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="stop" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="city" type="xs:string" minOccurs="0"/>
							<xs:element name="address" type="xs:string" minOccurs="0"/>
							<xs:element name="phone-number" type="xs:string" minOccurs="0"/>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="trains">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="train" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="stop" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="time" type="xs:string"/>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="days" type="xs:string"/>
</xs:schema>

=== ericdaugherty/ericdaugherty.github.io/trainschedule/mdn.xml
<?xml version="1.0" encoding="Cp1252"?>

<schedule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.ericdaugherty.com/trainschedule/trainschedule.xsd">
  <route name="Milwaukee District North;">
    <inbound>
      <days>M-F</days>
      <stops>
        <stop name="Fox Lake" />
        <stop name="Ingleside" />
        <stop name="Long Lake" />
        <stop name="Round Lake" />
        <stop name="Grayslake" />
        <stop name="Libertyville" />
        <stop name="Lake Forest" />
        <stop name="Deerfield" />
        <stop name="Lake Cook Road" />
        <stop name="Northbrook" />
        <stop name="Glen/N. Glenview" />
        <stop name="Glenview" />
        <stop name="Golf" />
        <stop name="Morton Grove" />
        <stop name="Edgebrook" />
        <stop name="Forest Glen" />
        <stop name="Mayfair" />
        <stop name="Grayland" />
        <stop name="Healy" />
        <stop name="Western Ave" />
        <stop name="Chicago Union Sta" />
      </stops>
      <trains>
        <train name="2102">
          <stop name="Fox Lake">
            <time>4:48</time>
          </stop>
          <stop name="Ingleside">
            <time>4:51</time>
          </stop>
          <stop name="Long Lake">
            <time>4:55</time>
          </stop>
          <stop name="Round Lake">
            <time>4:58</time>
          </stop>
          <stop name="Grayslake">
            <time>5:02</time>
          </stop>
          <stop name="Libertyville">
            <time>5:10</time>
          </stop>
          <stop name="Lake Forest">
            <time>5:20</time>
          </stop>
          <stop name="Deerfield">
            <time>5:26</time>
          </stop>
          <stop name="Lake Cook Road">
            <time>5:29</time>
          </stop>
          <stop name="Northbrook">
            <time>5:33</time>
          </stop>
          <stop name="Glen/N. Glenview">
            <time>5:38</time>
          </stop>
          <stop name="Glenview">
            <time>5:41</time>
          </stop>
          <stop name="Golf">
            <time>5:44</time>
          </stop>
          <stop name="Morton Grove">
            <time>5:47</time>
          </stop>
          <stop name="Edgebrook">
            <time>5:51</time>
          </stop>
          <stop name="Forest Glen">
            <time>5:54</time>
          </stop>
          <stop name="Mayfair">
            <time>5:57</time>
          </stop>
          <stop name="Grayland">
            <time>5:59</time>
          </stop>
          <stop name="Healy">
            <time>6:02</time>
          </stop>
          <stop name="Western Ave">
            <time>6:06</time>
          </stop>
          <stop name="Chicago Union Sta">
            <time>6:19</time>
          </stop>
        </train>
        <train name="2104">
          <stop name="Fox Lake">
            <time>5:15</time>
          </stop>
          <stop name="Ingleside">
            <time>5:18</time>
          </stop>
          <stop name="Long Lake">
            <time>5:22</time>
          </stop>
          <stop name="Round Lake">
            <time>5:25</time>
          </stop>
          <stop name="Grayslake">
            <time>5:29</time>
          </stop>
          <stop name="Libertyville">
            <time>5:37</time>
          </stop>
          <stop name="Lake Forest">
            <time>5:48</time>
          </stop>
          <stop name="Deerfield">
            <time>5:54</time>
          </stop>
          <stop name="Lake Cook Road">
            <time>5:57</time>
          </stop>
          <stop name="Northbrook">
            <time>6:01</time>
          </stop>
          <stop name="Glen/N. Glenview">
            <time>6:06</time>
          </stop>
          <stop name="Glenview">
            <time>6:09</time>
          </stop>
          <stop name="Golf">
            <time>6:12</time>
          </stop>
          <stop name="Morton Grove">
            <time>6:15</time>
          </stop>
          <stop name="Edgebrook">
            <time>6:20</time>
          </stop>
          <stop name="Forest Glen">
            <time>6:23</time>
          </stop>
          <stop name="Mayfair">
            <time>6:26</time>
          </stop>
          <stop name="Grayland">
            <time>6:28</time>
          </stop>
          <stop name="Healy">
            <time>6:32</time>
          </stop>
          <stop name="Western Ave">
            <time>6:38</time>
          </stop>
          <stop name="Chicago Union Sta">
            <time>6:51</time>
          </stop>
        </train>
        <train name="2106">
          <stop name="Fox Lake">
            <time>5:36</time>
          </stop>
          <stop name="Ingleside">
            <time>5:39</time>
          </stop>
          <stop name="Long Lake">
            <time>5:43</time>
          </stop>
          <stop name="Round Lake">
            <time>5:47</time>
          </stop>
          <stop name="Grayslake">
            <time>5:53</time>
          </stop>
          <stop name="Libertyville">
            <time>6:02</time>
          </stop>
          <stop name="Lake Forest">
            <time>6:13</time>
          </stop>
          <stop name="Deerfield">
            <time>6:19</time>
          </stop>
          <stop name="Lake Cook Road">
            <time>6:22</time>
          </stop>
          <stop name="Northbrook">
            <time>6:26</time>
          </stop>
          <stop name="Glen/N. Glenview">
            <time>6:31</time>
          </stop>
          <stop name="Glenview">
            <time>6:34</time>
          </stop>
          <stop name="Golf">
            <time>6:37</time>
          </stop>
          <stop name="Morton Grove">
            <time>6:41</time>
          </stop>
          <stop name="Edgebrook">
            <time>6:46</time>
          </stop>
          <stop name="Forest Glen">
            <time>6:49</time>
          </stop>
          <stop name="Mayfair">
            <time>6:52</time>
          </stop>
          <stop name="Grayland">
            <time>6:54</time>
          </stop>
          <stop name="Healy">
            <time>6:58</time>
          </stop>
          <stop name="Western Ave">
            <time>7:04</time>
          </stop>
          <stop name="Chicago Union Sta">
            <time>7:16</time>
          </stop>
        </train>
        <train name="2108">
          <stop name="Fox Lake">
            <time>6:08</time>
          </stop>
          <stop name="Ingleside">
            <time>-----</time>
          </stop>
          <stop name="Long Lake">
            <time>-----</time>
          </stop>
          <stop name="Round Lake">
            <time>-----</time>
          </stop>
          <stop name="Grayslake">
            <time>-----</time>
          </stop>
          <stop name="Libertyville">
            <time>6:26</time>
          </stop>
          <stop name="Lake Forest">
            <time>6:37</time>
          </stop>
          <stop name="Deerfield">
            <time>6:44</time>
          </stop>
          <stop name="Lake Cook Road">
            <time>-----</time>
          </stop>
          <stop name="Northbrook">
            <time>6:50</time>
          </stop>
          <stop name="Glen/N. Glenview">
            <time>-----</time>
          </stop>
          <stop name="Glenview">
            <time>6:57</time>
          </stop>
          <stop name="Golf">
            <time>7:00</time>
          </stop>
          <stop name="Morton Grove">
            <time>7:04</time>
          </stop>
          <stop name="Edgebrook">
            <time>-----</time>
          </stop>
          <stop name="Forest Glen">
            <time>-----</time>
          </stop>
          <stop name="Mayfair">
            <time>-----</time>
          </stop>
          <stop name="Grayland">
            <time>-----</time>
          </stop>
          <stop name="Healy">
            <time>-----</time>
          </stop>
          <stop name="Western Ave">
            <time>7:20</time>
          </stop>
          <stop name="Chicago Union Sta">
            <time>7:32</time>
          </stop>
        </train>
        <train name="2110">
          <stop name="Fox Lake">
            <time>6:16</time>
          </stop>
          <stop name="Ingleside">
            <time>6:20</time>
          </stop>
          <stop name="Long Lake">
            <time>6:23</time>
          </stop>
          <stop name="Round Lake">
            <time>6:27</time>
          </stop>
          <stop name="Grayslake">
            <time>6:32</time>
          </stop>
          <stop name="Libertyville">
            <time>6:41</time>
          </stop>
          <stop name="Lake Forest">
            <time>-----</time>
          </stop>
          <stop name="Deerfield">
            <time>-----</time>
          </stop>
          <stop name="Lake Cook Road">
            <time>6:57</time>
          </stop>
          <stop name="Northbrook">
            <time>-----</time>
          </stop>
          <stop name="Glen/N. Glenview">
            <time>7:05</time>
          </stop>
          <stop name="Glenview">
            <time>-----</time>
          </stop>
          <stop name="Golf">
            <time>-----</time>
          </stop>
          <stop name="Morton Grove">
            <time>7:12</time>
          </stop>
          <stop name="Edgebrook">
            <time>7:17</time>
          </stop>
          <stop name="Forest Glen">
            <time>7:20</time>
          </stop>
          <stop name="Mayfair">
            <time>7:24</time>
          </stop>
          <stop name="Grayland">
            <time>7:26</time>
          </stop>
          <stop name="Healy">
            <time>7:30</time>
          </stop>
          <stop name="Western Ave">
            <time>7:36</time>
          </stop>
          <stop name="Chicago Union Sta">
            <time>7:48</time>
          </stop>
